### ISSUE TITLE
COMP: Compilation errors on Clang 15.0

### ISSUE THREAD

**Issue by Kutalmis-Bercin** [AUfluids/KOSSTPDA#1]
Hi @aligiw @mjavrincon,

We do get various compilation errors for the following environment:

```
    base1    = develop
    api      = 2401
    patch    = 240220
    HEAD     = 0ef981adbc
    version  = v2312
    compiler = Clang (system)         = clang version 15.0.7
    mpi      = SYSTEMOPENMPI        = mpirun (Open MPI) 1.10.7.0.5e373bf1fd
    OS       = Description:     openSUSE Leap 15.5
    opts     = linux64ClangDPInt32Opt
```

An example error:

```
./kOmegaSSTPDABase.C:726:20: error: conversion from 'tmp<GeometricField<typename outerProduct<vector, Vector<double>>::type, Foam::fvPatchField, Foam::volMesh>>' (aka 'tmp<GeometricField<Tensor<double>, Foam::fvPatchField, Foam::volMesh>>') to 'Foam::volTensorField' (aka 'GeometricField<Tensor<double>, Foam::fvPatchField, Foam::volMesh>') is ambiguous
    volTensorField gradU = fvc::grad(U);
```

Steps to reproduce:

```
// Source OpenFOAM-dev with Clang 15.0
// Clone the repo
// Execute Allwmake - which needs to be transformed to an executable as well
```

Potential solution (not tested):

```
// Either
tmp<volTensorField> tgradU = fvc::grad(U);
const auto& gradU = tgradU.cref();
// or
const volTensorField gradU(fvc::grad(U));
// See for further info: https://develop.openfoam.com/Development/openfoam/-/wikis/coding/patterns/patterns 
```

Would you mind looking at the issue (preferred way), or do you want us to push the fixes?

Many thanks for your contributions and time.

Kind regards, Kuti

**Comment by mjavrincon** [comment]
Hi Kuti,

Thanks for the heads up. We did not test the compilation for that specific
configuration.

We have tried the compilation with the fix:

const volTensorField gradU(fvc::grad(U));

And we do not get any errors. But again, we do not have that
environment in our computers so we do not know how to test it
specifically for it.

If you do not mind, we believe that you can push it with those fixes.
Please, let us know if there are any issues.

Unfortunately, we are not experts in OpenFOAM's coding and some
concepts slip through the cracks to us.

Best regards,


Mario J. Rincón

**Comment by Kutalmis-Bercin** [comment]
related: #2
