### ISSUE TITLE
Request: Tag

### ISSUE THREAD

**Issue by Kutalmis-Bercin** [AUfluids/KOSSTPDA#3]
Hello @mjavrincon @aligiw 

Could you please add a tag for v2406 so that OpenFOAM submodules can have a non-moving target SHA?

Many thanks.

**Comment by mjavrincon** [comment]
Hi Kutalmis,

I have created the tag. I hope that everything is in order :)

**Comment by Kutalmis-Bercin** [comment]
Hi @mjavrincon - Thank you very much!
